
import java.awt.Color;
import java.awt.Font;
import java.io.Serializable;
import javax.swing.BorderFactory;
import static javax.swing.JOptionPane.showMessageDialog;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class Hint extends javax.swing.JPanel implements Serializable{
    String cad=""; //Creamos una variable para almacenar el hint
    /**
     * Creates new form NewJPanel
     */
    public Hint() {
        initComponents();
        jTextField1.setBorder(BorderFactory.createLineBorder(Color.cyan, 1));
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();

        jTextField1.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setText("jTextField1");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        //Entra a este metodo si el textfield esta en foucus
        if(jTextField1.getText().equals(cad)){ //Si el textfield es igual al hint
            jTextField1.setBorder(BorderFactory.createLineBorder(Color.black, 1));
            jTextField1.setText(""); //Borramos para colocar información 
            jTextField1.setForeground(Color.BLACK); //Le colocamos el color en negritas
        }
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        if(jTextField1.getText().equals("")){ //Si el textfield se encuentra vacio perdiendo el focus
            jTextField1.setBorder(BorderFactory.createLineBorder(Color.cyan, 1));
            jTextField1.setText(cad); //Colocamos el hint que colocamos
            jTextField1.setForeground(Color.gray); //Le devolvemos el color del hint
        }
    }//GEN-LAST:event_jTextField1FocusLost
    //Hacemos un metodo Hint donde atraeremos lo que el usuario capturo en el hint
    public String getHint(){
        return this.cad;
    }
    //El otro metodo coloca el hit que nosotros colocamos en la cadena
    public void setHint(String t){
        this.cad = t;
    }
    //Sobreescribimos el metodo getText para cuando entre al focus compare si existe un hint
    public String getText() {
        return jTextField1.getText();
    }
    //Sobreescribimos el metodo setText para cuando queramos colocar texto en el TextField
    public void setText(String text) {   
        jTextField1.setText(text);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables


}
